#Métodos Numéricos / Examen Parcial 2
## 30 puntos

7 de abril, 2022

_____________________________________
## José Eduardo Sierra Del Río
_____________________________________

_____________________________________
<font color='blue'>  
 1. (6pt) Poner en forma lineal las siguientes expresiones:<br>
(a) $y = C\,e^{Dx}$<br>
(b) $y = \frac{1}{1 + E\,e^{Dx}}$<br>
(c) $y = \bigg(\frac{A + \sqrt{x}}{B\sqrt{x}} \bigg)^2$<br>
</font>

<font color='white'>
Respuestas:<br>
(a) $ln(y) = Dx + ln(c)$<br>
(b) $ln(y^{-1}-1) = Dx + ln(E)$<br>
(c) $y^{2} = \frac{A\sqrt{x}}{Bx} + \frac{1}{B}$<br>
</font>

_____________________________________
<font color='blue'>   
2. (6pt) Explique de manera concisa qué hace cada una de las líneas del siguiente algoritmo:
</font>

In [ ]:
import numpy as np

T = np.ones((5,5))
m = len(T)
Z = np.zeros((m,m))

for l in range(m):
    for c in range(m-1,0,-1):
        Z[l,c] = l - c

print(Z)

5
[[ 0. -1. -2. -3. -4.]
 [ 0.  0. -1. -2. -3.]
 [ 0.  1.  0. -1. -2.]
 [ 0.  2.  1.  0. -1.]
 [ 0.  3.  2.  1.  0.]]


<font color='white'>
1. Importa numpy al codigo.<br>
2. Crea una matriz llamada T, la cual haciendo uso de la función ones de numpy obtiene un tamaño de 5x5 y es rellenada de "1".<br>
3. Se crea un numero llamado m cuyo valor es la longitud de T.<br>
4. Se crea una matriz del mismo tamaño que T pero que contiene unicamente "0".<br>
5. Se declara un ciclo for que recorre los valores de los indices de la matriz Z en "y".<br>
6. Se anida un ciclo for que recorre el intervalo de valores [4,3,2,1,0] (subindices de forma inversa).<br>
7. Se asigna a la dirección (l,c) de Z el valores l - c.<br>
8. Al finalizar el ciclo principal se imprimen los nuevos valores de Z.
</font>

_____________________________________
<font color='blue'>  
3. (6pt) Encuentre los 3 errores, indíquelos y corrija. 
</font>

In [ ]:
def regresion_lineal(x,y):

    n = len(x)
    sx = np.sum(x)
    sy = np.sum(y)
    sxy = np.sum(x*y)
    sx2 = np.sum(x*x)
    sy2 = np.sum(np.asarray(y)*np.asarray(y)) #Error, no se pueden multiplicar las listas de esta manera, se soluciona con np.asarray
    y_promedio = np.sum(y)/n #Error, n no estaba definida, era ne, se cambia ne por n

    a1 = (n*sxy - sx*sy)/(n*sx2 - sx*sx)
    a0 = (sx2*sy - sx*sxy)/(n*sx2 - sx*sx)

    sr = np.sum((y - a0 - a1*x)**2)
    st = np.sum((y - y_promedio)**2)
    de = np.sqrt(st/(n - 1))
    ee = np.sqrt(sr/(n - 2)) #Error, es np
    Coef_r = np.sqrt((st - sr)/st)
    return a0, a1, Coef_r, ee

x0 = np.array([0.5, 1, 2, 3, 4])
y0 = [10.4,5.8,3.3,2.4,2]

a0_fit, a1_fit, r, std_err = regresion_lineal(x0,y0)
print("a0 = ", a0_fit, "a1 = ", a1_fit, " r = ", r)

a0 =  9.233536585365853 a1 =  -2.120731707317073  r =  0.8746475795695153


_____________________________________
<font color='blue'>   
4. (6pt) Encuentre la matriz A de la cual se derivaron las siguientes matrices al aplicar descomposición LU:<br>
   (8pt) Si lo resuelves con ciclos 'for'
</font>

In [ ]:
L=np.array([[1,0,0,0],[2,1,0,0],[3,4,1,0],[-1,-3,0,1]], dtype=float)
U=np.array([[1,1,0,3],[0,-1,-1,-5],[0,0,3,13], [0,0,0,-13]], dtype=float)
n = len(L)
A = np.zeros((n,n))
for i in range(n):
  for j in range(n):
    aux = 0
    for k in range(n):
      aux += L[i][k]*U[k][j]
    A[i][j] = aux
print(A)

[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]


_____________________________________
<font color='blue'>   
5. (6pt) Utilice el código de eliminación Gaussiana hecho en clase para resolver:

En promedio, el área superficial A de los seres humanos se relaciona con el peso W y la estatura H. En la tabla siguiente se presentan los valores de A que se obtuvieron con mediciones de cierto número de individuos:<br>
<br>
A(m2) 1.92 2.11 2.15 2.02 2.09 2.31 2.02 2.16 2.31<br>
H(cm) 182 180 179 187 189 194 195 193 200<br>
W(kg) 74 88 94 78 84 98 76 86 96<br>
<br>
Desarrolle una ecuación lineal múltiple para pronosticar el área como función de la estatura y el peso. Utilícela para estimar el área superficial de una persona de 187 cm y 78 kg.
</font>


In [ ]:
def EliminacionGaussiana(a,b):
    n = len(b)
    for k in range(0,(n-1)): 
        if a[k,k] == 0:
            if a[k+1,k] != 0:
                temporal_a = np.copy(a[k,:])
                temporal_b = np.copy(b[k])
                a[k,:]  = a[k+1,:]
                b[k]  = b[k+1]
                a[k+1,:] = temporal_a
                b[k+1] = temporal_b

        for i in range(k+1,n):  
            m = a[i,k]/a[k,k]
            for j in range(0,n):  
                a[i,j] = a[i,j] - m*a[k,j] 
            b[i] = b[i] - m * b[k]

    x = np.zeros(n)
    x[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        s = 0
        for j in range(k,n): 
            s = s + a[k,j] * x[j]
        x[k] = (b[k] - s)/a[k,k]
    return x

In [77]:
HW = [[182,180,179,187,189,194,195,193,200],[74, 88, 94, 78, 84, 98, 76, 86, 96]]
A = [1.92, 2.11, 2.15, 2.02, 2.09, 2.31, 2.02, 2.16, 2.31]
syi = 0
sx1iyi = 0
sx2iyi = 0
n1 = len(A)
sx1i = 0
sx2i = 0
sx1i2 = 0
sx1ix2i = 0
sx2i2 = 0
for n in range(n1):
  sx1i += HW[0][n]
  sx2i += HW[1][n]
  sx1i2 += HW[0][n]**2
  sx1ix2i += HW[0][n]*HW[1][n]
  sx2i2 += HW[1][n]**2
  syi += A[n]
  sx1iyi += HW[0][n]*A[n]
  sx2iyi += HW[1][n]*A[n]
a = np.array([[n1,sx1i,sx2i],
     [sx1i,sx1i2,sx1ix2i],
     [sx2i,sx1ix2i,sx2i2]])
b = np.array([syi, sx1iyi, sx2iyi])
coef = np.zeros((n,n+1))
C = EliminacionGaussiana(a,b)
R = C[0]+187*C[1]+78*C[2]
print(R)

2.00791145959351
